#! /usr/bin/env bash

set -euo pipefail

readonly TARGET_DIR="${HOME}/Downloads/"
readonly UNDEF_VALUE="undefined"

readonly tag="$(git describe --tags)"

if [[ "${tag}" == "${UNDEF_VALUE}" ]]; then
    >&2 echo
    >&2 echo "You have to be on tagged commit!"
    exit 1
fi

tar -czvf "${TARGET_DIR}/shell-tea-timer.${tag}.tar.gz" shell-tea-timer conf libs vendor README.md LICENSE
