#! /usr/bin/env bash

set -euo pipefail

# -- global variables ---------------------------------------------------------

readonly STT_OS_LINUX="linux"
readonly STT_OS_MACOS="macos"

# -- os detection -------------------------------------------------------------

STT_OS="$(uname)"

case "${STT_OS}" in
    Linux)
        STT_OS="${STT_OS_LINUX}"
    ;;

    Darwin)
        STT_OS="${STT_OS_MACOS}"
    ;;

    *)
        >&2 echo
        >&2 echo "[${STT_OS}] is not supported operating system."
        exit 1
esac

# -- absolute dirpath ---------------------------------------------------------

ABSOLUTE_DIRPATH="$( cd "$( dirname "$( [[ -L "${BASH_SOURCE[0]}" ]] && readlink "${BASH_SOURCE[0]}" || echo "${BASH_SOURCE[0]}" )" )" && pwd )" || { \
    >&2 echo
    >&2 echo "Cannot determine real path of the script."
    exit 1
}

# -- global variables ---------------------------------------------------------

readonly _STT_RESET_OPTION="r"
readonly _STT_HELP_OPTION="h"
readonly _STT_SETUP_ARGUMENT="setup"

readonly UNDEF_VALUE="undef"

readonly LIBS_DIRPATH="${ABSOLUTE_DIRPATH}/libs"
readonly VENDOR_DIRPATH="${ABSOLUTE_DIRPATH}/vendor"
readonly CONF_DIRPATH="${ABSOLUTE_DIRPATH}/conf"
readonly TEAS_CONF_DIRPATH="${CONF_DIRPATH}/teas"
readonly POTS_CONF_DIRPATH="${CONF_DIRPATH}/pots"

readonly SLOWNESS_COMPENSATION_FACTOR=1

readonly MINIMUM_DECANT_TIME=3
readonly DECANT_RATIO=0.6

TEA="${UNDEF_VALUE}"
POT="${UNDEF_VALUE}"
TEA_NAME="${UNDEF_VALUE}"
TEA_INITIAL_INFUSION_DURATION="${UNDEF_VALUE}"
TEA_NEXT_INFUSION_DURATION="${UNDEF_VALUE}"
TEA_NUMBER_OF_INFUSIONS="${UNDEF_VALUE}"
TEA_BREWING_TEMP="${UNDEF_VALUE}"
TEA_AMOUNT_PER_100G="${UNDEF_VALUE}"
POT_NAME="${UNDEF_VALUE}"
POT_DECANT_DURATION="${UNDEF_VALUE}"
POT_CAPACITY_WITH_LEAVES="${UNDEF_VALUE}"

# -- load libraries -----------------------------------------------------------

# shellcheck source=vendor/fidian/ansi/ansi
. "${VENDOR_DIRPATH}/fidian/ansi/ansi"

# shellcheck source=libs/utils
. "${LIBS_DIRPATH}/utils"

# shellcheck source=libs/io
. "${LIBS_DIRPATH}/io"

# shellcheck source=libs/gfx
. "${LIBS_DIRPATH}/gfx"

# shellcheck source=libs/inputparser
. "${LIBS_DIRPATH}/inputparser"

# shellcheck source=libs/helpers
. "${LIBS_DIRPATH}/helpers"

# shellcheck source=libs/format
. "${LIBS_DIRPATH}/format"

# shellcheck source=libs/debug
. "${LIBS_DIRPATH}/debug"

# -- function definition ------------------------------------------------------

function stt::reset_infusion_counter() {
    local tea="${1}"

    stt::io::write_param "${tea}" "${IO_PARAM_TEA_INFUSION_COUNTER}" "0"

    echo
    echo "Reseting $(ansi --bold "${TEA_NAME}") infusion counter."
}

function stt::water_temp() {
    echo "${TEA_BREWING_TEMP}$(printf '%s' $'\xc2\xb0')C"
}

function stt::calculate_amount() {
    echo "$(echo "scale=1;${POT_CAPACITY_WITH_LEAVES}/100*${TEA_AMOUNT_PER_100G}" | bc) g"
}

function stt::calculate_start_of_decanting_raw() {
    echo "scale=0;(${POT_DECANT_DURATION}*${DECANT_RATIO})/1" | bc
}

function stt::calculate_start_of_decanting() {
    local start_of_decanting
    start_of_decanting="$(stt::calculate_start_of_decanting_raw)"

    printf '%s' "$(stt::format::format_seconds "${start_of_decanting}")"
}

function stt::setup_tea_params() {
    local tea="${1}"
    local tea_config_filepath

    TEA="${tea}"
    tea_config_filepath="$(stt::io::discover_tea_conf_files | grep "${tea}")" || return 1

    # shellcheck source=conf/teas/green.conf
    source "${TEAS_CONF_DIRPATH}/${tea_config_filepath}"

    stt::utils::check_if_set "tea name" "${TEA_NAME}"
    stt::utils::check_if_set "initial infusion duration" "${TEA_INITIAL_INFUSION_DURATION}"
    stt::utils::check_if_set "next infusion duration" "${TEA_NEXT_INFUSION_DURATION}"
    stt::utils::check_if_set "number of infusions" "${TEA_NUMBER_OF_INFUSIONS}"
    stt::utils::check_if_set "brewing temperature" "${TEA_BREWING_TEMP}"
    stt::utils::check_if_set "amount per 100g" "${TEA_AMOUNT_PER_100G}"
}

function stt::setup_pot_params() {
    local tea="${1}"
    local pot_config_filepath

    POT="$(stt::io::read_param "${tea}" "${IO_PARAM_POT}")" || exit ${?}
    pot_config_filepath="$(stt::io::discover_pot_conf_files | grep "${POT}")" || return 1

    # shellcheck source=conf/pots/glass.conf
    source "${POTS_CONF_DIRPATH}/${pot_config_filepath}"

    stt::utils::check_if_set "pot name" "${POT_NAME}"
    stt::utils::check_if_set "pot decant duration" "${POT_DECANT_DURATION}"
    stt::utils::check_if_set "pot capacity with leaves" "${POT_CAPACITY_WITH_LEAVES}"
}

function stt::setup_params_if_valid_tea() {
    local tea="${1}"

    stt::setup_tea_params "${tea}" || return 1
    stt::setup_pot_params "${tea}" || return 1

    TEA_INFUSION_COUNTER="$(stt::io::read_param_grace "${TEA}" "${IO_PARAM_TEA_INFUSION_COUNTER}" || printf '0')"

    return 0
}

function stt::get_start_command() {
    printf '%s %s' "$(basename "${0}")" "${TEA}"
}

function stt::setup_pot() {
    echo
    ansi --bold --no-newline "Choose a pot you want to brew in: "
    POT="$(stt::io::discover_pot_conf_files | rev | cut -c 6- | rev | sort | fzf)" || stt::utils::terminate "You have to choose a pot!"
    stt::io::write_param "${TEA}" "${IO_PARAM_POT}" "${POT}"
    stt::setup_pot_params "${TEA}"
    ansi --bold --no-newline "Choose a pot you want to brew in: "
    ansi "${POT_NAME}"
}

function stt::setup() {
    # TODO: check if FZF is installed
    echo
    ansi --bold --no-newline "Choose a tea you want to brew: "
    TEA="$(stt::io::discover_tea_conf_files | rev | cut -c 6- | rev | sort | fzf)" || stt::utils::terminate "You have to choose a tea!"
    stt::setup_tea_params "${TEA}"
    ansi --bold --no-newline "Choose a tea you want to brew: "
    ansi "${TEA_NAME}"

    TEA_INFUSION_COUNTER="$(stt::io::read_param_grace "${TEA}" "${IO_PARAM_TEA_INFUSION_COUNTER}" || printf '0')"
    POT="$(stt::io::read_param_grace "${TEA}" "${IO_PARAM_POT}" || printf '%s' "${UNDEF_VALUE}")"

    local ANSWER_NEW_SESSION="new session"
    local ANSWER_RESET="reset infusion counter"
    local ANSWER_SET="set infusion counter"
    local action_message="What action do you want to do?"
    local action answer
    local action_list=( "${ANSWER_NEW_SESSION}" )

    if [[ "${TEA_INFUSION_COUNTER}" -gt 0 ]]; then
        action_message="Previous session found with $(stt::format::format_infusion_number). ${action_message}"
        action_list+=( "${ANSWER_RESET}" "${ANSWER_SET}" )
    else
        action_list+=( "${ANSWER_SET}" )
    fi

    if [[ "${POT}" != "${UNDEF_VALUE}" ]]; then
        stt::setup_pot_params "${TEA}"
    fi

    # ověřit, že to není nějaké mega staré

    echo
    ansi --bold --no-newline "${action_message} "
    action="$(echo -e "$(IFS=$'\n'; printf '%s' "${action_list[*]}")" | fzf)" || stt::utils::terminate "You have to choose an action!"
    stt::setup_tea_params "${TEA}"
    ansi --bold --no-newline "${action_message} "
    ansi "${action}"

    case "${action}" in
        "${ANSWER_NEW_SESSION}" )
            stt::setup_pot
        ;;

        "${ANSWER_RESET}" )
            stt::reset_infusion_counter "${TEA}"

            # maybe ask, if wants to set pot?
            stt::setup_pot
        ;;

        "${ANSWER_SET}" )
            echo
            ansi --bold --no-newline "How many infusions have you had? "
            read -r answer

            if [[ "${answer}" =~ ^[0-9]+$ ]]; then
                stt::io::write_param "${TEA}" "${IO_PARAM_TEA_INFUSION_COUNTER}" "${answer}"
            else
                stt::utils::terminate "[${answer}] is not a number!"
            fi

            if [[ "${POT}" != "${UNDEF_VALUE}" ]]; then
                stt::setup_pot
            fi
        ;;

        * )
            stt::utils::terminate "Unknown action [${action}]."
    esac

    echo
    echo "Heat your water to $(ansi --bold "$(stt::water_temp)")."

    echo
    echo "Use $(ansi --bold "$(stt::calculate_amount)") of leaves (${TEA_AMOUNT_PER_100G} g per 100 ml, pot capacity is ${POT_CAPACITY_WITH_LEAVES} ml)."

    local command
    command="$(stt::get_start_command)"

    echo
    ansi --bold "Your command has been copied to your clipboard!"
    printf "%s" "${command}" | pbcopy
}

# -- initial setup ------------------------------------------------------------

stt::utils::check_prerequisites

stt::inputparser::parse_input "${@}"

TEA_INFUSION_COUNTER="$(( TEA_INFUSION_COUNTER + 1 ))"
stt::io::write_param "${TEA}" "${IO_PARAM_TEA_INFUSION_COUNTER}" "${TEA_INFUSION_COUNTER}"

if [[ "${TEA_INFUSION_COUNTER}" -eq "${TEA_NUMBER_OF_INFUSIONS}" ]]; then
    say "Poslední nálev!" &
elif [[ "${TEA_INFUSION_COUNTER}" -gt "${TEA_NUMBER_OF_INFUSIONS}" ]]; then
    say "Už jsi přes čáru." &
fi

# -- main program -------------------------------------------------------------

tea_countdown="$(( TEA_INITIAL_INFUSION_DURATION + (TEA_INFUSION_COUNTER - 1) * TEA_NEXT_INFUSION_DURATION ))"

echo
echo "You are brewing $(ansi --bold "${TEA_NAME}") in $(ansi --bold "${POT_NAME}") pot."
echo "This is your $(ansi --bold "$(stt::format::format_infusion_number_ordinal)") infusion out of $(ansi --bold "${TEA_NUMBER_OF_INFUSIONS}")."
echo "Infuse for $(ansi --bold "${tea_countdown} seconds") in $(ansi --bold "$(stt::water_temp)") water."
echo "Decanting should start $(ansi --bold "$(stt::calculate_start_of_decanting)") earlier."
stt::gfx::countdown_start "${tea_countdown}"
echo "Decant your tea now!"
say "Do píči čaj."

stt::debug::report_compensasion_factor
