#! /usr/bin/env bash

STT_TEA_SESSION_HIST_ENABLED=0

function flow::ask_main_action() {
    local action_new_session="Start new session"
    local action_load_session="Load existing session"
    local action_exit="Exit program"
    local main_action_list=( "${action_new_session}" "${action_load_session}" "${action_exit}" )
    local main_action_message="What would you like to do?"
    local action

    echo
    ansi --bold --no-newline "${main_action_message} "
    action="$(echo -e "$(IFS=$'\n'; printf '%s' "${main_action_list[*]}")" | fzf --no-mouse)" || utils::terminate "You have to choose an action!"
    ansi --bold --no-newline "${main_action_message} "
    ansi "${action}"

    case "${action}" in
        "${action_new_session}" )
            flow::new_session_action
        ;;

        "${action_load_session}" )
            flow::load_session_action
        ;;

        "${action_exit}" )
            :
        ;;

        * )
            utils::terminate "Unknown action [${action}]."
    esac
}

function flow::ask_tea() {
    local message="Choose a tea you want to brew:"

    echo
    ansi --bold --no-newline "${message} "
    setup::setup_tea
    ansi --bold --no-newline "${message} "
    ansi "${TEA_NAME}"
}

function flow::ask_pot() {
    local message="Choose a pot you want to brew in:"

    echo
    ansi --bold --no-newline "${message} "
    setup::setup_pot
    ansi --bold --no-newline "${message} "
    ansi "${POT_NAME}"
}

function flow::ask_existing_session() {
    local action_message="What existing session would you like to load?"
    local chosen_tea_session
    local discovered_tea_sessions=()
    local tea

    while IFS=$'\n' read -r tea_session; do
        discovered_tea_sessions+=( "${tea_session}" )
    done < <(io::discover_tea_sessions)

    echo
    ansi --bold --no-newline "${action_message} "
    chosen_tea_session="$(echo -e "$(IFS=$'\n'; printf '%s' "${discovered_tea_sessions[*]}")" | fzf --no-mouse)" || utils::terminate "You have to choose existing tea session!"
    ansi --bold --no-newline "${action_message} "
    ansi "${chosen_tea_session}"

    echo
    ansi --bold "Loading existing session."
    tea="$(echo "${chosen_tea_session}" | cut -d ':' -f 1)"
    setup::setup_params_if_valid_tea "${tea}"
}

function flow::ask_modify_params() {
    local answer_next_infusion_duration
    local answer_number_of_infusions
    local action_message

    action_message="Next infusion duration:"

    echo
    ansi --bold --no-newline "${action_message} "
    read -r answer_next_infusion_duration
    ansi --no-newline --up --delete-line
    ansi --bold --no-newline "${action_message} "
    ansi "${answer_next_infusion_duration}"

    action_message="Number of total infusions:"

    ansi --bold --no-newline "${action_message} "
    read -r answer_number_of_infusions
    ansi --no-newline --up --delete-line
    ansi --bold --no-newline "${action_message} "
    ansi "${answer_number_of_infusions}"

    setup::modify_params \
        "${answer_next_infusion_duration}" \
        "${answer_number_of_infusions}"
}

function flow::end_current_session() {
    local action_log_and_remove_session="Log & remove tea session"
    local action_backup_session="Backup tea session for later"
    local action_list=( "${action_log_and_remove_session}" "${action_backup_session}" )
    local action_message="What should happen to this tea session?"
    local action

    echo
    ansi --bold --no-newline "${action_message} "
    action="$(echo -e "$(IFS=$'\n'; printf '%s' "${action_list[*]}")" | fzf --no-mouse)" || utils::terminate "You have to choose an action!"
    ansi --bold --no-newline "${action_message} "
    ansi "${action}"

    case "${action}" in
        "${action_log_and_remove_session}" )
            echo
            ansi --bold "Removing this tea session."
            io::remove_tea_session_data "${TEA}"
            flow::log_finished_tea_session
        ;;

        "${action_backup_session}" )
            echo
            ansi --bold "Backing up this tea session for later."
        ;;

        * )
            utils::terminate "Unknown action [${action}]."
    esac
}

function flow::new_session_action() {
    flow::ask_tea

    flow::ask_pot

    gfx::show_recommended_water_temp

    gfx::show_recommended_leaf_amount

    flow::start_session 0
}

function flow::load_session_action() {
    flow::ask_existing_session

    gfx::show_recommended_water_temp

    flow::start_session "${TEA_INFUSION_COUNTER}"
}

function flow::start_session() {
    local tea_infusion_counter="${1}"

    local action_end_session="End session"
    local action_next_infusion="Next infusion"
    local action_modify_params="Modify brewing parameters"
    local action_list=( "${action_next_infusion}" "${action_end_session}" "${action_modify_params}" )
    local action_message="How would you like to continue?"
    local action
    local ready_to_start

    echo
    ansi --bold --no-newline "Press [enter] when you are ready to start."
    read -r ready_to_start

    TEA_INFUSION_COUNTER="${tea_infusion_counter}"

    while true; do
        TEA_INFUSION_COUNTER="$(( TEA_INFUSION_COUNTER + 1 ))"
        io::write_param "${TEA}" "${IO_PARAM_TEA_INFUSION_COUNTER}" "${TEA_INFUSION_COUNTER}"

        if [[ "${TEA_INFUSION_COUNTER}" -eq "${TEA_NUMBER_OF_INFUSIONS}" ]]; then
            audio::announce "${ANNOUNCEMENT_LAST_INFUSION}" &
        elif [[ "${TEA_INFUSION_COUNTER}" -gt "${TEA_NUMBER_OF_INFUSIONS}" ]]; then
            audio::announce "${ANNOUNCEMENT_TOO_MANY_INFUSIONS}" &
        fi

        infuse_duration="$(( TEA_INITIAL_INFUSION_DURATION + (TEA_INFUSION_COUNTER - 1) * TEA_NEXT_INFUSION_DURATION ))"

        echo
        echo "You are brewing $(ansi --bold "${TEA_NAME}") in $(ansi --bold "${POT_NAME}") pot."
        echo "This is your $(ansi --bold "$(formattting::format_infusion_number_ordinal "${TEA_INFUSION_COUNTER}")") infusion out of $(ansi --bold "${TEA_NUMBER_OF_INFUSIONS}")."
        echo "Infuse for $(ansi --bold "$(formatting::format_seconds "${infuse_duration}")") in $(ansi --bold "$(helpers::water_temp)") water."
        echo "Decanting should start $(ansi --bold "$(helpers::calculate_start_of_decanting)") earlier."
        gfx::countdown_start "${infuse_duration}"
        echo "Decant your tea now!"
        audio::announce "${ANNOUNCEMENT_DECANT_NOW}" &

        while true; do
            echo
            ansi --bold --no-newline "${action_message} "
            action="$(echo -e "$(IFS=$'\n'; printf '%s' "${action_list[*]}")" | fzf --no-mouse)" || utils::terminate "You have to choose an action!"
            ansi --bold --no-newline "${action_message} "
            ansi "${action}"

            case "${action}" in
                "${action_end_session}" )
                    flow::end_current_session
                    break 2;
                ;;

                "${action_modify_params}" )
                    flow::ask_modify_params
                ;;

                "${action_next_infusion}" )
                    break
                ;;

                * )
                    utils::terminate "Unknown action [${action}]."
            esac
        done

        echo
        echo
        echo
        echo
        echo
    done
}

function flow::check_tea_session_logging() {
    if [[ -z "${STT_TEA_SESSION_LOG_FILEPATH+_}" ]]; then
        echo
        ansi --bold --red "Environment variable \$STT_TEA_SESSION_LOG_FILEPATH is not set, logging finished tea session is disabled!"
        return
    fi

    STT_TEA_SESSION_HIST_ENABLED=1
}

function flow::init() {
    setup::setup_announcement_params
}

function flow::log_finished_tea_session() {
    echo
    ansi --bold "Saving tea session."
    io::log_finished_tea_session
}

function flow::goodbye() {
    echo
    echo "Thank you for using Shell Tea Timer (by hologos)."
}

function flow::main() {
    echo
    echo "Welcome to Shell Tea Timer ({{{version}}}, {{{generated_on}}})"

    flow::init

    flow::check_tea_session_logging

    flow::ask_main_action

    flow::goodbye
}
