#! /usr/bin/env bash

function formatting::format_seconds() {
    local seconds="${1}"
    local placeholder="second"

    if [[ "${seconds}" -ne 1 ]]; then
        placeholder+="s"
    fi

    printf '%s %s' "${seconds}" "${placeholder}"
}

function formatting::format_infusion_number_ordinal() {
    local tea_infusion_counter="${1}"

    printf '%s' "${tea_infusion_counter}"

    case "${tea_infusion_counter}" in
        1) echo "st";;
        2) echo "nd";;
        3) echo "rd";;
        *) echo "th";;
    esac
}

function formatting::format_infusion_number() {
    local tea_infusion_counter="${1}"

    printf '%s infusion' "${tea_infusion_counter}"

    if [[ "${tea_infusion_counter}" -ne 1 ]]; then
        echo "s"
    else
        echo
    fi
}
