#! /usr/bin/env bash

readonly _OPTION_HELP="-h"
readonly _OPTION_CONFIG_DIRPATH="-c"

function inputparser::usage() {
    # shellcheck disable=SC2155
    local fmt_bold="$(ansi --bold --no-restore)"
    # shellcheck disable=SC2155
    local fmt_underline="$(ansi --underline --no-restore)"
    # shellcheck disable=SC2155
    local fmt_reset="$(ansi --reset-attrib)"

    >&2 echo
    >&2 echo "Usage: ${0} [-${_OPTION_HELP}] [-${_OPTION_CONFIG_DIRPATH} <configs-dirpath>]"
    >&2 echo
    >&2 echo "    ${fmt_bold}-${_OPTION_HELP}${fmt_reset}"
    >&2 echo "        Prints this help."
    >&2 echo
    >&2 echo "    ${fmt_bold}-${_OPTION_CONFIG_DIRPATH} <configs-dirpath>${fmt_reset}"
    >&2 echo "        Dirpath to configs directory."
    >&2 echo
    >&2 echo "${fmt_underline}Environment variables${fmt_reset}"
    >&2 echo "    ${fmt_bold}STT_CONFIG_DITPATH${fmt_reset} - dirpath to configs directory"
}

function inputparser::parse_input() {
    while [[ ${#} -ne 0 ]] && [[ "${1}" != "" ]]; do
        local input="${1}"

        case "${input}" in

            "${_OPTION_HELP}" )
                inputparser::usage
                utils::terminate
            ;;

            "${_OPTION_CONFIG_DIRPATH}" )
                shift
                STT_CONFIG_DITPATH="${1}"
            ;;

            * )
                inputparser::usage
                utils::terminate "Unknown option [${input}]."
        esac

        shift
    done

    io::init
}
