#! /usr/bin/env bash

function setup::setup_tea_params() {
    local tea="${1}"
    local tea_config_filepath

    TEA="${tea}"
    tea_config_filepath="$(io::discover_tea_conf_files | grep "${tea}")" || return 1

    # shellcheck source=../conf/teas/generic-green.conf
    source "${TEAS_CONF_DIRPATH}/${tea_config_filepath}"

    utils::check_if_set "tea name" "${TEA_NAME}"
    utils::check_if_set "initial infusion duration" "${TEA_INITIAL_INFUSION_DURATION}"
    utils::check_if_set "next infusion duration" "${TEA_NEXT_INFUSION_DURATION}"
    utils::check_if_set "number of infusions" "${TEA_NUMBER_OF_INFUSIONS}"
    utils::check_if_set "brewing temperature" "${TEA_BREWING_TEMP}"
    utils::check_if_set "amount per 100g" "${TEA_AMOUNT_PER_100G}"
}

function setup::setup_pot_params() {
    local tea="${1}"
    local pot_config_filepath

    POT="$(io::read_param "${tea}" "${IO_PARAM_POT}")" || exit ${?}
    pot_config_filepath="$(io::discover_pot_conf_files | grep "${POT}")" || return 1

    # shellcheck source=../conf/pots/generic-pot.conf
    source "${POTS_CONF_DIRPATH}/${pot_config_filepath}"

    utils::check_if_set "pot name" "${POT_NAME}"
    utils::check_if_set "pot decant duration" "${POT_DECANT_DURATION}"
    utils::check_if_set "pot capacity with leaves" "${POT_CAPACITY_WITH_LEAVES}"
}

function setup::setup_params_if_valid_tea() {
    local tea="${1}"

    setup::setup_tea_params "${tea}" || return 1
    setup::setup_pot_params "${tea}" || return 1

    TEA_INFUSION_COUNTER="$(io::read_param_grace "${TEA}" "${IO_PARAM_TEA_INFUSION_COUNTER}" || printf '0')"

    return 0
}

function setup::setup_pot() {
    POT="$(io::discover_pot_conf_files | rev | cut -c 6- | rev | sort | fzf)" || utils::terminate "You have to choose a pot!"
    io::write_param "${TEA}" "${IO_PARAM_POT}" "${POT}"
    setup::setup_pot_params "${TEA}"
}

function setup::setup_tea() {
    TEA="$(io::discover_tea_conf_files | rev | cut -c 6- | rev | sort | fzf)" || utils::terminate "You have to choose a tea!"
    setup::setup_tea_params "${TEA}"
}
